%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/ubuntu/Desktop/Data/Sonuçlar/CW09BRuntopicss.xlsx
%    Worksheet: MAPTransposed
%
% Auto-generated by MATLAB on 11-Apr-2020 21:02:19

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "NDCG100Transposed";
opts.DataRange = "BN2:BU1525";

% Specify column names and types
opts.VariableNames = ["RID","NoStem","KStemQBS","SnowballEngQBS","HPS","Gupta","KStem" ,"SnowballEng"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
MQ07_NDCG100_DFRee = readtable("/home/ubuntu/Desktop/Data/Sonuçlar/MQ07RuntopicsTransposed.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts