%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/ubuntu/Desktop/Data/Features/FeatureCW09BKStem.txt
%
% Auto-generated by MATLAB on 08-May-2020 17:50:12

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 46);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["QueryID", "WordCount", "Gamma", "Omega", "AvgPMI", "MaxPMI", "SCS", "MeanICTF", "VarICTF", "MeanIDF", "MaxIDF", "VarIDF", "MeanCTI", "VarCTI", "MaxCTI", "MeanSkew", "VarSkew", "MeanKurt", "VarKurt", "MeanSCQ", "VarSCQ", "MaxSCQ", "SumSCQ", "MeanCommonality", "VarCommonality", "SCCS", "MeanSCCQ", "VarSCCQ", "MeanAdvance", "MaxAdvance", "VarAdvance", "MeanAdvanceTF", "MaxAdvanceTF", "VarAdvanceTF", "MeanAdvanceDF", "MaxAdvanceDF", "VarAdvanceDF", "BM25", "DLM", "LGD", "PL2", "DFIC", "DPH", "DLH13", "DFRee", "AvgQL"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "WordCount", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["QueryID", "Gamma", "Omega", "AvgPMI", "MaxPMI", "SCS", "MeanICTF", "VarICTF", "MeanIDF", "MaxIDF", "VarIDF", "MeanCTI", "VarCTI", "MaxCTI", "MeanSkew", "VarSkew", "MeanKurt", "VarKurt", "MeanSCQ", "VarSCQ", "MaxSCQ", "SumSCQ", "MeanCommonality", "VarCommonality", "SCCS", "MeanSCCQ", "VarSCCQ", "MeanAdvance", "MaxAdvance", "VarAdvance", "MeanAdvanceTF", "MaxAdvanceTF", "VarAdvanceTF", "MeanAdvanceDF", "MaxAdvanceDF", "VarAdvanceDF", "BM25", "DLM", "LGD", "PL2", "DFIC", "DPH", "DLH13", "DFRee", "AvgQL"], "FillValue", 0);

% Import the data
FeatureWSJLovins = readtable("/home/ubuntu/Desktop/Data/Features/FeatureWSJLovins.txt", opts);


%% Clear temporary variables
clear opts