%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/ubuntu/Desktop/Data/Features/FeatureCW09BKStem.txt
%
% Auto-generated by MATLAB on 05-May-2020 15:37:12

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 32);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["QueryID", "WordCount", "Gamma", "Omega", "AvgPMI", "SCS", "MeanICTF", "VarICTF", "MeanIDF", "VarIDF", "MeanCTI", "VarCTI", "MeanSkew", "VarSkew", "MeanKurt", "VarKurt", "MeanSCQ", "VarSCQ", "MeanCommonality", "VarCommonality", "SCCS", "MeanSCCQ", "VarSCCQ", "Advance", "BM25", "DLM", "LGD", "PL2", "DFIC", "DPH", "DLH13", "DFRee"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "WordCount", "EmptyFieldRule", "auto");

% Import the data
FeatureCW09BSnowballEng = readtable("/home/ubuntu/Desktop/Data/Features/FeatureCW09BSnowball.txt", opts);


%% Clear temporary variables
clear opts