%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/ubuntu/Desktop/Data/Features/FeatureWSJSnowballEngTerm.txt
%
% Auto-generated by MATLAB on 12-May-2020 20:50:49

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["QueryID", "word", "DFNoStem", "TFNoStem", "ictfs", "idfs", "ctis", "skew", "kurt", "scqs", "commonalities", "DF", "TF", "idfStem", "sccq", "DocLenAcc", "advance", "advanceTF", "advanceDF", "BM25", "DLM", "LGD", "PL2", "DFIC", "DPH", "DLH13", "DFRee", "QL"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];


% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "word", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "word", "EmptyFieldRule", "auto");

% Import the data
FeatureCW12BKStemTerm = readtable("/home/ubuntu/Desktop/Data/Features/FeatureCW12BKStemTerm.txt", opts);


%% Clear temporary variables
clear opts