function [trainedModel, validationRMSE, yfit, predictorNames] = trainLinearInteractionReg(trainingData,testData)
% [trainedModel, validationRMSE] = trainRegressionModel(trainingData)
% Returns a trained regression model and its RMSE. This code recreates the
% model trained in Regression Learner app. Use the generated code to
% automate training the same model with new data, or to learn how to
% programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedModel: A struct containing the trained regression model. The
%       struct contains various fields with information about the trained
%       model.
%
%      trainedModel.predictFcn: A function to make predictions on new data.
%
%      validationRMSE: A double containing the RMSE. In the app, the
%       History list displays the RMSE for each model.
%
% Use the code to train the model with new data. To retrain your model,
% call the function from the command line with your original data or new
% data as the input argument trainingData.
%
% For example, to retrain a regression model trained with the original data
% set T, enter:
%   [trainedModel, validationRMSE] = trainRegressionModel(T)
%
% To make predictions with the returned 'trainedModel' on new data T2, use
%   yfit = trainedModel.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedModel.HowToPredict

% Auto-generated by MATLAB on 31-May-2020 00:36:24


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'WordCount', 'Gamma', 'Omega', 'AvgPMI', 'MaxPMI', 'SCS', 'MeanICTF', 'VarICTF', 'MeanIDF', 'VarIDF', 'MaxIDF', 'MeanCTI', 'VarCTI', 'MaxCTI', 'MeanSkew', 'VarSkew', 'MeanKurt', 'VarKurt', 'MeanSCQ', 'VarSCQ', 'MaxSCQ', 'SumSCQ', 'MeanCommonality', 'VarCommonality', 'SCCS', 'MeanSCCQ', 'VarSCCQ', 'MeanAdvance', 'MaxAdvance', 'VarAdvance', 'MeanAdvanceTF', 'MaxAdvanceTF', 'VarAdvanceTF', 'MeanAdvanceDF', 'MaxAdvanceDF', 'VarAdvanceDF', 'AvgQL', 'mean_IdfAdvDF', 'max_IdfAdvDF', 'sum_IdfAdvDF', 'var_IdfAdvDF', 'min_IdfAdvDF', 'mean_CtiAdvDF', 'max_CtiAdvDF', 'sum_CtiAdvDF', 'var_CtiAdvDF', 'mean_idfRatio', 'max_idfRatio', 'sum_idfRatio', 'var_idfRatio', 'min_idfRatio', 'mean_idfStem', 'max_idfStem', 'var_idfStem', 'idfRatioMinMax', 'correlationTerms', 'lstmstTerms', 'GammaStem', 'Chi2DFTF'};
predictors = inputTable(:, predictorNames);
response = inputTable.Diff;
isCategoricalPredictor = [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Data transformation: Select subset of the features
% This code selects the same subset of features as were used in the app.
includedPredictorNames = predictors.Properties.VariableNames([false true false true true true true true true true true true true true true true true true true true true true true true false false false false false false false false false false false false true false false false false false false false false false false false false false false false false false false false true false false]);
predictors = predictors(:,includedPredictorNames);
isCategoricalPredictor = isCategoricalPredictor([true true false true true true true true true true true true true true true true true true true true true true true true false false false false false false false false false false false false true false false false false false false false false false false false false false false false false false false false true false false]);

% Train a regression model
% This code specifies all the model options and trains the model.
concatenatedPredictorsAndResponse = normalize(predictors);
concatenatedPredictorsAndResponse.Diff = response;
linearModel = fitlm(...
    concatenatedPredictorsAndResponse, ...
    'interactions', ...
    'RobustOpts', 'off');

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
featureSelectionFcn = @(x) x(:,includedPredictorNames);
linearModelPredictFcn = @(x) predict(linearModel, x);
trainedModel.predictFcn = @(x) linearModelPredictFcn(featureSelectionFcn(predictorExtractionFcn(x)));

% Add additional fields to the result struct
trainedModel.RequiredVariables = {'AvgPMI', 'AvgQL', 'Chi2DFTF', 'Gamma', 'GammaStem', 'MaxAdvance', 'MaxAdvanceDF', 'MaxAdvanceTF', 'MaxCTI', 'MaxIDF', 'MaxPMI', 'MaxSCQ', 'MeanAdvance', 'MeanAdvanceDF', 'MeanAdvanceTF', 'MeanCTI', 'MeanCommonality', 'MeanICTF', 'MeanIDF', 'MeanKurt', 'MeanSCCQ', 'MeanSCQ', 'MeanSkew', 'Omega', 'SCCS', 'SCS', 'SumSCQ', 'VarAdvance', 'VarAdvanceDF', 'VarAdvanceTF', 'VarCTI', 'VarCommonality', 'VarICTF', 'VarIDF', 'VarKurt', 'VarSCCQ', 'VarSCQ', 'VarSkew', 'WordCount', 'correlationTerms', 'idfRatioMinMax', 'lstmstTerms', 'max_CtiAdvDF', 'max_IdfAdvDF', 'max_idfRatio', 'max_idfStem', 'mean_CtiAdvDF', 'mean_IdfAdvDF', 'mean_idfRatio', 'mean_idfStem', 'min_IdfAdvDF', 'min_idfRatio', 'sum_CtiAdvDF', 'sum_IdfAdvDF', 'sum_idfRatio', 'var_CtiAdvDF', 'var_IdfAdvDF', 'var_idfRatio', 'var_idfStem'};
trainedModel.LinearModel = linearModel;
trainedModel.About = 'This struct is a trained model exported from Regression Learner R2020a.';
trainedModel.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appregression_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'WordCount', 'Gamma', 'Omega', 'AvgPMI', 'MaxPMI', 'SCS', 'MeanICTF', 'VarICTF', 'MeanIDF', 'VarIDF', 'MaxIDF', 'MeanCTI', 'VarCTI', 'MaxCTI', 'MeanSkew', 'VarSkew', 'MeanKurt', 'VarKurt', 'MeanSCQ', 'VarSCQ', 'MaxSCQ', 'SumSCQ', 'MeanCommonality', 'VarCommonality', 'SCCS', 'MeanSCCQ', 'VarSCCQ', 'MeanAdvance', 'MaxAdvance', 'VarAdvance', 'MeanAdvanceTF', 'MaxAdvanceTF', 'VarAdvanceTF', 'MeanAdvanceDF', 'MaxAdvanceDF', 'VarAdvanceDF', 'AvgQL', 'mean_IdfAdvDF', 'max_IdfAdvDF', 'sum_IdfAdvDF', 'var_IdfAdvDF', 'min_IdfAdvDF', 'mean_CtiAdvDF', 'max_CtiAdvDF', 'sum_CtiAdvDF', 'var_CtiAdvDF', 'mean_idfRatio', 'max_idfRatio', 'sum_idfRatio', 'var_idfRatio', 'min_idfRatio', 'mean_idfStem', 'max_idfStem', 'var_idfStem', 'idfRatioMinMax', 'correlationTerms', 'lstmstTerms', 'GammaStem', 'Chi2DFTF'};
predictors = inputTable(:, predictorNames);
response = inputTable.Diff;
isCategoricalPredictor = [true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

validationPredictFcn = @(x) linearModelPredictFcn(featureSelectionFcn(x));

% Compute resubstitution predictions
validationPredictions = validationPredictFcn(predictors);

% Compute validation RMSE
isNotMissing = ~isnan(validationPredictions) & ~isnan(response);
validationRMSE = sqrt(nansum(( validationPredictions - response ).^2) / numel(response(isNotMissing) ));

yfit = trainedModel.predictFcn(testData);
